[build-system]
requires = ["hatchling >= 1.18"]
build-backend = "hatchling.build"

[project]
name = "uc"
dynamic = ["version"]
readme = "README.md"
authors = [{name = "Tiago de Paula Alves"}]
requires-python = ">= 3.5"
dependencies = [
    "graphviz",
    "llvmlite",
    "ply",
    "pytest",
]

[tool.hatch.version]
path = "uc/__init__.py"
pattern = "__version__: Final = '(?P<version>[^']+)'"

[tool.hatch.build.targets.sdist]
include = ["uc/"]

[tool.black]
line-length = 99
